import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { sql } from "drizzle-orm";
import { db } from "@/lib/db";

vi.mock("next/cache", () => ({
  revalidatePath: vi.fn(),
}));

vi.mock("@/lib/auth/session", () => ({
  getSessionUser: vi.fn().mockResolvedValue({ id: 1, email: "test@test.local", name: "Test" }),
  getSessionUserOrNull: vi
    .fn()
    .mockResolvedValue({ id: 1, email: "test@test.local", name: "Test" }),
}));

const {
  createRule,
  updateRule,
  toggleRuleActive,
  deleteRule,
  downgradeAutoGeneratedRule,
  approveRuleProposal,
  denyRuleProposal,
} = await import("./actions");

const TEST_USER_ID = 1;
const PATTERN_PREFIX = "TEST-RULES-ACTIONS-";

const PROPOSAL_PREFIX = "TEST-RULES-PROP-";

async function cleanup() {
  await db.execute(sql`
    DELETE FROM classification_rules
    WHERE user_id = ${TEST_USER_ID}
      AND (pattern LIKE ${PATTERN_PREFIX + "%"} OR pattern LIKE ${"%" + PROPOSAL_PREFIX + "%"})
  `);
  await db.execute(sql`
    DELETE FROM rule_proposals
    WHERE user_id = ${TEST_USER_ID} AND merchant LIKE ${PROPOSAL_PREFIX + "%"}
  `);
}

async function seedProposal(args: {
  merchant: string;
  categorySlug: string;
  correctionTxnIds: number[];
  status?: "pending" | "approved" | "denied";
}): Promise<number> {
  const rows = await db.execute<{ id: number }>(sql`
    INSERT INTO rule_proposals (
      user_id, merchant, category_slug, correction_txn_ids, status
    ) VALUES (
      ${TEST_USER_ID},
      ${args.merchant},
      ${args.categorySlug},
      ${JSON.stringify(args.correctionTxnIds)}::jsonb,
      ${args.status ?? "pending"}::rule_proposal_status
    )
    RETURNING id
  `);
  return rows[0].id;
}

async function seedRule(args: {
  pattern: string;
  categorySlug: string;
  priority?: number;
  active?: boolean;
  autoGenerated?: boolean;
  generatedFromCorrections?: number[] | null;
}): Promise<number> {
  const rows = await db.execute<{ id: number }>(sql`
    INSERT INTO classification_rules (
      user_id, pattern, category_slug, priority, active, auto_generated, generated_from_corrections
    ) VALUES (
      ${TEST_USER_ID},
      ${args.pattern},
      ${args.categorySlug},
      ${args.priority ?? 100},
      ${args.active ?? true},
      ${args.autoGenerated ?? false},
      ${args.generatedFromCorrections ? JSON.stringify(args.generatedFromCorrections) : null}::jsonb
    )
    RETURNING id
  `);
  return rows[0].id;
}

beforeEach(cleanup);
afterEach(cleanup);

describe("createRule", () => {
  it("creates a rule with auto_generated=false by default", async () => {
    const result = await createRule({
      pattern: `${PATTERN_PREFIX}%CARULLA%`,
      categorySlug: "alimentacion",
      priority: 120,
    });

    expect(result).toEqual({ status: "ok" });

    const rows = await db.execute<{
      pattern: string;
      category_slug: string;
      priority: number;
      active: boolean;
      auto_generated: boolean;
    }>(sql`
      SELECT pattern, category_slug, priority, active, auto_generated
      FROM classification_rules
      WHERE user_id = ${TEST_USER_ID} AND pattern = ${PATTERN_PREFIX + "%CARULLA%"}
    `);
    expect(rows).toHaveLength(1);
    expect(rows[0].category_slug).toBe("alimentacion");
    expect(rows[0].priority).toBe(120);
    expect(rows[0].active).toBe(true);
    expect(rows[0].auto_generated).toBe(false);
  });

  it("rejects when category does not exist for the user", async () => {
    const result = await createRule({
      pattern: `${PATTERN_PREFIX}%X%`,
      categorySlug: "no-existe",
      priority: 100,
    });
    expect(result).toEqual({
      status: "error",
      message: "La categoría no existe o está archivada.",
    });
  });

  it("rejects duplicate (pattern, category) with a clear message", async () => {
    await seedRule({
      pattern: `${PATTERN_PREFIX}%DUP%`,
      categorySlug: "alimentacion",
    });
    const result = await createRule({
      pattern: `${PATTERN_PREFIX}%DUP%`,
      categorySlug: "alimentacion",
    });
    expect(result).toEqual({
      status: "error",
      message: "Ya tenés una regla con ese patrón y categoría.",
    });
  });

  it("rejects empty pattern via zod", async () => {
    const result = await createRule({
      pattern: "",
      categorySlug: "alimentacion",
    });
    expect(result.status).toBe("error");
  });
});

describe("updateRule", () => {
  it("updates pattern, category, priority on an existing rule", async () => {
    const id = await seedRule({
      pattern: `${PATTERN_PREFIX}%OLD%`,
      categorySlug: "alimentacion",
      priority: 100,
    });

    const result = await updateRule({
      id,
      pattern: `${PATTERN_PREFIX}%NEW%`,
      categorySlug: "transferencias",
      priority: 50,
    });

    expect(result).toEqual({ status: "ok" });
    const rows = await db.execute<{
      pattern: string;
      category_slug: string;
      priority: number;
    }>(sql`
      SELECT pattern, category_slug, priority
      FROM classification_rules WHERE id = ${id}
    `);
    expect(rows[0].pattern).toBe(`${PATTERN_PREFIX}%NEW%`);
    expect(rows[0].category_slug).toBe("transferencias");
    expect(rows[0].priority).toBe(50);
  });

  it("returns error when rule belongs to a different user", async () => {
    const result = await updateRule({
      id: 9_999_999,
      pattern: `${PATTERN_PREFIX}%X%`,
      categorySlug: "alimentacion",
      priority: 100,
    });
    expect(result).toEqual({ status: "error", message: "Regla no encontrada." });
  });
});

describe("toggleRuleActive", () => {
  it("flips active from true to false and back", async () => {
    const id = await seedRule({
      pattern: `${PATTERN_PREFIX}%TOGGLE%`,
      categorySlug: "alimentacion",
      active: true,
    });

    const off = await toggleRuleActive({ id, active: false });
    expect(off).toEqual({ status: "ok" });

    const [rowOff] = await db.execute<{ active: boolean }>(sql`
      SELECT active FROM classification_rules WHERE id = ${id}
    `);
    expect(rowOff.active).toBe(false);

    const on = await toggleRuleActive({ id, active: true });
    expect(on).toEqual({ status: "ok" });
    const [rowOn] = await db.execute<{ active: boolean }>(sql`
      SELECT active FROM classification_rules WHERE id = ${id}
    `);
    expect(rowOn.active).toBe(true);
  });
});

describe("deleteRule", () => {
  it("hard-deletes the row", async () => {
    const id = await seedRule({
      pattern: `${PATTERN_PREFIX}%DEL%`,
      categorySlug: "alimentacion",
    });

    const result = await deleteRule({ id });
    expect(result).toEqual({ status: "ok" });

    const rows = await db.execute(sql`
      SELECT 1 FROM classification_rules WHERE id = ${id}
    `);
    expect(rows).toHaveLength(0);
  });

  it("returns error when the rule does not exist", async () => {
    const result = await deleteRule({ id: 9_999_999 });
    expect(result).toEqual({ status: "error", message: "Regla no encontrada." });
  });
});

describe("approveRuleProposal", () => {
  it("creates an auto-generated rule from a pending proposal and marks it approved", async () => {
    const merchant = `${PROPOSAL_PREFIX}CARULLA`;
    const proposalId = await seedProposal({
      merchant,
      categorySlug: "alimentacion",
      correctionTxnIds: [8271, 8342, 8401],
    });

    const result = await approveRuleProposal({ id: proposalId });
    expect(result).toEqual({ status: "ok" });

    const [rule] = await db.execute<{
      pattern: string;
      category_slug: string;
      auto_generated: boolean;
      generated_from_corrections: number[] | null;
    }>(sql`
      SELECT pattern, category_slug, auto_generated, generated_from_corrections
      FROM classification_rules
      WHERE user_id = ${TEST_USER_ID} AND pattern = ${`%${merchant}%`}
    `);
    expect(rule.pattern).toBe(`%${merchant}%`);
    expect(rule.category_slug).toBe("alimentacion");
    expect(rule.auto_generated).toBe(true);
    expect(rule.generated_from_corrections).toEqual([8271, 8342, 8401]);

    const [prop] = await db.execute<{ status: string; decided_at: Date | null }>(sql`
      SELECT status::text, decided_at FROM rule_proposals WHERE id = ${proposalId}
    `);
    expect(prop.status).toBe("approved");
    expect(prop.decided_at).not.toBeNull();

    // Cleanup the extra rule we just created.
    await db.execute(sql`
      DELETE FROM classification_rules WHERE pattern = ${`%${merchant}%`}
    `);
  });

  it("refuses to approve a proposal that is already decided", async () => {
    const merchant = `${PROPOSAL_PREFIX}ALREADY`;
    const proposalId = await seedProposal({
      merchant,
      categorySlug: "alimentacion",
      correctionTxnIds: [1, 2, 3],
      status: "approved",
    });

    const result = await approveRuleProposal({ id: proposalId });
    expect(result).toEqual({
      status: "error",
      message: "Esa propuesta ya fue decidida.",
    });
  });

  it("returns error when proposal does not exist", async () => {
    const result = await approveRuleProposal({ id: 9_999_999 });
    expect(result).toEqual({ status: "error", message: "Propuesta no encontrada." });
  });

  it("surfaces a friendly message when approving would create a duplicate rule", async () => {
    const merchant = `${PROPOSAL_PREFIX}DUPE`;
    const proposalId = await seedProposal({
      merchant,
      categorySlug: "alimentacion",
      correctionTxnIds: [1, 2, 3],
    });
    await db.execute(sql`
      INSERT INTO classification_rules (user_id, pattern, category_slug)
      VALUES (${TEST_USER_ID}, ${`%${merchant}%`}, 'alimentacion')
    `);

    const result = await approveRuleProposal({ id: proposalId });
    expect(result.status).toBe("error");
    if (result.status === "error") {
      expect(result.message).toContain("Ya existe una regla");
    }

    // Proposal stays pending — failed approve should not mark as decided.
    const [prop] = await db.execute<{ status: string }>(sql`
      SELECT status::text FROM rule_proposals WHERE id = ${proposalId}
    `);
    expect(prop.status).toBe("pending");
  });
});

describe("denyRuleProposal", () => {
  it("marks a pending proposal as denied and stamps decided_at", async () => {
    const merchant = `${PROPOSAL_PREFIX}DENY`;
    const proposalId = await seedProposal({
      merchant,
      categorySlug: "alimentacion",
      correctionTxnIds: [1, 2, 3],
    });

    const result = await denyRuleProposal({ id: proposalId });
    expect(result).toEqual({ status: "ok" });

    const [prop] = await db.execute<{ status: string; decided_at: Date | null }>(sql`
      SELECT status::text, decided_at FROM rule_proposals WHERE id = ${proposalId}
    `);
    expect(prop.status).toBe("denied");
    expect(prop.decided_at).not.toBeNull();
  });

  it("refuses to deny a proposal that is already decided", async () => {
    const merchant = `${PROPOSAL_PREFIX}DENY-DONE`;
    const proposalId = await seedProposal({
      merchant,
      categorySlug: "alimentacion",
      correctionTxnIds: [1, 2, 3],
      status: "denied",
    });

    const result = await denyRuleProposal({ id: proposalId });
    expect(result).toEqual({
      status: "error",
      message: "Propuesta no encontrada o ya decidida.",
    });
  });
});

describe("downgradeAutoGeneratedRule", () => {
  it("clears auto_generated and generated_from_corrections", async () => {
    const id = await seedRule({
      pattern: `${PATTERN_PREFIX}%AUTO%`,
      categorySlug: "alimentacion",
      autoGenerated: true,
      generatedFromCorrections: [8271, 8342, 8401],
    });

    const result = await downgradeAutoGeneratedRule({ id });
    expect(result).toEqual({ status: "ok" });

    const [row] = await db.execute<{
      auto_generated: boolean;
      generated_from_corrections: number[] | null;
    }>(sql`
      SELECT auto_generated, generated_from_corrections
      FROM classification_rules WHERE id = ${id}
    `);
    expect(row.auto_generated).toBe(false);
    expect(row.generated_from_corrections).toBeNull();
  });

  it("refuses to downgrade a rule that is already manual", async () => {
    const id = await seedRule({
      pattern: `${PATTERN_PREFIX}%MANUAL%`,
      categorySlug: "alimentacion",
      autoGenerated: false,
    });

    const result = await downgradeAutoGeneratedRule({ id });
    expect(result).toEqual({
      status: "error",
      message: "Regla no encontrada o no es auto-generada.",
    });
  });
});
