"use server";

import { revalidatePath } from "next/cache";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/lib/db";
import { categories, classificationRules, ruleProposals } from "@/lib/db/schema";
import { notDeleted } from "@/lib/db/helpers";
import { getSessionUser } from "@/lib/auth/session";

const patternSchema = z.string().trim().min(1).max(200);
const categorySlugSchema = z.string().min(1).max(60);
const prioritySchema = z.number().int().min(1).max(10000);

const createSchema = z.object({
  pattern: patternSchema,
  categorySlug: categorySlugSchema,
  priority: prioritySchema.default(100),
});

const updateSchema = z.object({
  id: z.number().int().positive(),
  pattern: patternSchema,
  categorySlug: categorySlugSchema,
  priority: prioritySchema,
});

const idSchema = z.object({ id: z.number().int().positive() });
const toggleSchema = z.object({ id: z.number().int().positive(), active: z.boolean() });

export type RuleActionResult = { status: "ok" } | { status: "error"; message: string };

function isUniqueViolation(err: unknown, constraintName: string): boolean {
  if (!err || typeof err !== "object") return false;
  const message = err instanceof Error ? err.message : "";
  if (message.includes(constraintName)) return true;
  const cause = (err as { cause?: unknown }).cause;
  if (cause && typeof cause === "object") {
    const code = (cause as { code?: unknown }).code;
    const name = (cause as { constraint_name?: unknown }).constraint_name;
    if (code === "23505" && name === constraintName) return true;
  }
  return false;
}

async function assertCategoryExists(userId: number, slug: string): Promise<boolean> {
  const [row] = await db
    .select({ slug: categories.slug })
    .from(categories)
    .where(
      and(
        eq(categories.userId, userId),
        eq(categories.slug, slug),
        notDeleted(categories.deletedAt),
      ),
    )
    .limit(1);
  return Boolean(row);
}

export async function createRule(input: z.input<typeof createSchema>): Promise<RuleActionResult> {
  const session = await getSessionUser();
  const parsed = createSchema.safeParse(input);
  if (!parsed.success) {
    return { status: "error", message: parsed.error.issues[0]?.message ?? "Input inválido." };
  }

  if (!(await assertCategoryExists(session.id, parsed.data.categorySlug))) {
    return { status: "error", message: "La categoría no existe o está archivada." };
  }

  try {
    await db.insert(classificationRules).values({
      userId: session.id,
      pattern: parsed.data.pattern,
      categorySlug: parsed.data.categorySlug,
      priority: parsed.data.priority,
      active: true,
      autoGenerated: false,
    });
  } catch (err) {
    // unique (user_id, pattern, category_slug) collision
    if (isUniqueViolation(err, "rules_user_pattern_category_unique")) {
      return { status: "error", message: "Ya tenés una regla con ese patrón y categoría." };
    }
    throw err;
  }

  revalidatePath("/settings/rules");
  return { status: "ok" };
}

export async function updateRule(input: z.input<typeof updateSchema>): Promise<RuleActionResult> {
  const session = await getSessionUser();
  const parsed = updateSchema.safeParse(input);
  if (!parsed.success) {
    return { status: "error", message: parsed.error.issues[0]?.message ?? "Input inválido." };
  }

  if (!(await assertCategoryExists(session.id, parsed.data.categorySlug))) {
    return { status: "error", message: "La categoría no existe o está archivada." };
  }

  try {
    const result = await db
      .update(classificationRules)
      .set({
        pattern: parsed.data.pattern,
        categorySlug: parsed.data.categorySlug,
        priority: parsed.data.priority,
      })
      .where(
        and(eq(classificationRules.userId, session.id), eq(classificationRules.id, parsed.data.id)),
      )
      .returning({ id: classificationRules.id });

    if (result.length === 0) {
      return { status: "error", message: "Regla no encontrada." };
    }
  } catch (err) {
    if (isUniqueViolation(err, "rules_user_pattern_category_unique")) {
      return { status: "error", message: "Ya tenés una regla con ese patrón y categoría." };
    }
    throw err;
  }

  revalidatePath("/settings/rules");
  return { status: "ok" };
}

export async function toggleRuleActive(
  input: z.input<typeof toggleSchema>,
): Promise<RuleActionResult> {
  const session = await getSessionUser();
  const parsed = toggleSchema.safeParse(input);
  if (!parsed.success) {
    return { status: "error", message: "Input inválido." };
  }

  const result = await db
    .update(classificationRules)
    .set({ active: parsed.data.active })
    .where(
      and(eq(classificationRules.userId, session.id), eq(classificationRules.id, parsed.data.id)),
    )
    .returning({ id: classificationRules.id });

  if (result.length === 0) {
    return { status: "error", message: "Regla no encontrada." };
  }

  revalidatePath("/settings/rules");
  return { status: "ok" };
}

export async function deleteRule(input: z.input<typeof idSchema>): Promise<RuleActionResult> {
  const session = await getSessionUser();
  const parsed = idSchema.safeParse(input);
  if (!parsed.success) {
    return { status: "error", message: "Input inválido." };
  }

  // Hard delete — rules are cheap to recreate and `copyRuleSeedsToUser` can
  // re-seed baseline rules if needed. If an auto-generated rule is deleted,
  // the learning loop in #317 will be free to re-propose it after 30 days.
  const result = await db
    .delete(classificationRules)
    .where(
      and(eq(classificationRules.userId, session.id), eq(classificationRules.id, parsed.data.id)),
    )
    .returning({ id: classificationRules.id });

  if (result.length === 0) {
    return { status: "error", message: "Regla no encontrada." };
  }

  revalidatePath("/settings/rules");
  return { status: "ok" };
}

export async function approveRuleProposal(
  input: z.input<typeof idSchema>,
): Promise<RuleActionResult> {
  const session = await getSessionUser();
  const parsed = idSchema.safeParse(input);
  if (!parsed.success) {
    return { status: "error", message: "Input inválido." };
  }

  try {
    await db.transaction(async (trx) => {
      const [proposal] = await trx
        .select({
          id: ruleProposals.id,
          merchant: ruleProposals.merchant,
          categorySlug: ruleProposals.categorySlug,
          correctionTxnIds: ruleProposals.correctionTxnIds,
          status: ruleProposals.status,
        })
        .from(ruleProposals)
        .where(and(eq(ruleProposals.userId, session.id), eq(ruleProposals.id, parsed.data.id)))
        .limit(1)
        .for("update");

      if (!proposal) throw new ProposalNotFoundError();
      if (proposal.status !== "pending") throw new ProposalAlreadyDecidedError();

      // Merchant wrapped in ILIKE wildcards. If merchant contains a literal %
      // the user can edit the rule after the fact; default keeps the common
      // case trivial.
      const pattern = `%${proposal.merchant}%`;

      await trx.insert(classificationRules).values({
        userId: session.id,
        pattern,
        categorySlug: proposal.categorySlug,
        priority: 100,
        active: true,
        autoGenerated: true,
        generatedFromCorrections: proposal.correctionTxnIds,
      });

      await trx
        .update(ruleProposals)
        .set({ status: "approved", decidedAt: new Date() })
        .where(eq(ruleProposals.id, proposal.id));
    });
  } catch (err) {
    if (err instanceof ProposalNotFoundError) {
      return { status: "error", message: "Propuesta no encontrada." };
    }
    if (err instanceof ProposalAlreadyDecidedError) {
      return { status: "error", message: "Esa propuesta ya fue decidida." };
    }
    if (isUniqueViolation(err, "rules_user_pattern_category_unique")) {
      return {
        status: "error",
        message: "Ya existe una regla con ese patrón y categoría — editala o elimínala primero.",
      };
    }
    throw err;
  }

  revalidatePath("/settings/rules");
  return { status: "ok" };
}

export async function denyRuleProposal(input: z.input<typeof idSchema>): Promise<RuleActionResult> {
  const session = await getSessionUser();
  const parsed = idSchema.safeParse(input);
  if (!parsed.success) {
    return { status: "error", message: "Input inválido." };
  }

  const result = await db
    .update(ruleProposals)
    .set({ status: "denied", decidedAt: new Date() })
    .where(
      and(
        eq(ruleProposals.userId, session.id),
        eq(ruleProposals.id, parsed.data.id),
        eq(ruleProposals.status, "pending"),
      ),
    )
    .returning({ id: ruleProposals.id });

  if (result.length === 0) {
    return { status: "error", message: "Propuesta no encontrada o ya decidida." };
  }

  revalidatePath("/settings/rules");
  return { status: "ok" };
}

class ProposalNotFoundError extends Error {}
class ProposalAlreadyDecidedError extends Error {}

export async function downgradeAutoGeneratedRule(
  input: z.input<typeof idSchema>,
): Promise<RuleActionResult> {
  const session = await getSessionUser();
  const parsed = idSchema.safeParse(input);
  if (!parsed.success) {
    return { status: "error", message: "Input inválido." };
  }

  const result = await db
    .update(classificationRules)
    .set({ autoGenerated: false, generatedFromCorrections: null })
    .where(
      and(
        eq(classificationRules.userId, session.id),
        eq(classificationRules.id, parsed.data.id),
        eq(classificationRules.autoGenerated, true),
      ),
    )
    .returning({ id: classificationRules.id });

  if (result.length === 0) {
    return { status: "error", message: "Regla no encontrada o no es auto-generada." };
  }

  revalidatePath("/settings/rules");
  return { status: "ok" };
}
