import { and, asc, eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { categories, classificationRules, ruleProposals } from "@/lib/db/schema";
import { notDeleted } from "@/lib/db/helpers";
import { getSessionUser } from "@/lib/auth/session";
import { RulesManager } from "./rules-manager";

export const dynamic = "force-dynamic";

export default async function RulesPage() {
  const session = await getSessionUser();
  const [cats, rules, proposals] = await Promise.all([
    db
      .select({
        slug: categories.slug,
        name: categories.name,
        parentSlug: categories.parentSlug,
      })
      .from(categories)
      .where(and(eq(categories.userId, session.id), notDeleted(categories.deletedAt)))
      .orderBy(asc(categories.sortOrder), asc(categories.name)),
    db
      .select({
        id: classificationRules.id,
        pattern: classificationRules.pattern,
        categorySlug: classificationRules.categorySlug,
        priority: classificationRules.priority,
        active: classificationRules.active,
        hitCount: classificationRules.hitCount,
        lastHitAt: classificationRules.lastHitAt,
        autoGenerated: classificationRules.autoGenerated,
        generatedFromCorrections: classificationRules.generatedFromCorrections,
        createdAt: classificationRules.createdAt,
      })
      .from(classificationRules)
      .where(eq(classificationRules.userId, session.id))
      .orderBy(asc(classificationRules.priority), asc(classificationRules.id)),
    db
      .select({
        id: ruleProposals.id,
        merchant: ruleProposals.merchant,
        categorySlug: ruleProposals.categorySlug,
        correctionTxnIds: ruleProposals.correctionTxnIds,
        createdAt: ruleProposals.createdAt,
      })
      .from(ruleProposals)
      .where(and(eq(ruleProposals.userId, session.id), eq(ruleProposals.status, "pending")))
      .orderBy(asc(ruleProposals.createdAt)),
  ]);

  const rows = rules.map((r) => ({
    ...r,
    lastHitAt: r.lastHitAt?.toISOString() ?? null,
    createdAt: r.createdAt.toISOString(),
  }));

  const pending = proposals.map((p) => ({
    ...p,
    createdAt: p.createdAt.toISOString(),
  }));

  return (
    <main className="mx-auto flex w-full max-w-5xl flex-col gap-4 p-4 sm:p-6">
      <header>
        <h1 className="text-h1">Reglas de clasificación</h1>
        <p className="text-body text-muted-foreground">
          Patrones ILIKE que se aplican a la descripción o el comercio de cada transacción antes del
          fallback con IA. Las reglas con 🤖 son auto-generadas por el learning loop — podés
          desactivarlas, editarlas o convertirlas a manuales si querés hacerlas tuyas.
        </p>
      </header>
      <RulesManager categories={cats} rules={rows} proposals={pending} />
    </main>
  );
}
