"use client";

import { Fragment, useMemo, useState, useTransition } from "react";
import {
  ChevronDownIcon,
  ChevronRightIcon,
  PencilIcon,
  PlusIcon,
  Trash2Icon,
  Undo2Icon,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";
import {
  approveRuleProposal,
  createRule,
  deleteRule,
  denyRuleProposal,
  downgradeAutoGeneratedRule,
  revertRuleRetroactive,
  toggleRuleActive,
  updateRule,
  type RulePreview,
} from "./actions";
import { ApplyRetroactiveModal } from "./apply-retroactive-modal";

type CategoryOption = {
  slug: string;
  name: string;
  parentSlug: string | null;
};

type RuleRow = {
  id: number;
  pattern: string;
  categorySlug: string;
  priority: number;
  active: boolean;
  hitCount: number;
  lastHitAt: string | null;
  autoGenerated: boolean;
  generatedFromCorrections: number[] | null;
  createdAt: string;
  retroactiveMatchCount: number;
};

type RetroactiveModalState = {
  open: boolean;
  ruleId: number | null;
  preview: RulePreview | null;
  targetCategorySlug: string | null;
};

const CLOSED_RETROACTIVE_MODAL: RetroactiveModalState = {
  open: false,
  ruleId: null,
  preview: null,
  targetCategorySlug: null,
};

type ProposalRow = {
  id: number;
  merchant: string;
  categorySlug: string;
  correctionTxnIds: number[];
  createdAt: string;
};

type EditorState = {
  open: boolean;
  editing: RuleRow | null;
};

function formatRelative(iso: string | null): string {
  if (!iso) return "nunca";
  const diffMs = Date.now() - Date.parse(iso);
  if (Number.isNaN(diffMs) || diffMs < 0) return "ahora";
  const min = Math.floor(diffMs / 60_000);
  if (min < 1) return "ahora";
  if (min < 60) return `hace ${min} min`;
  const hr = Math.floor(min / 60);
  if (hr < 24) return `hace ${hr} h`;
  const d = Math.floor(hr / 24);
  if (d < 30) return `hace ${d} d`;
  const mo = Math.floor(d / 30);
  if (mo < 12) return `hace ${mo} mes${mo === 1 ? "" : "es"}`;
  const yr = Math.floor(mo / 12);
  return `hace ${yr} año${yr === 1 ? "" : "s"}`;
}

export function RulesManager({
  categories,
  rules,
  proposals,
}: {
  categories: CategoryOption[];
  rules: RuleRow[];
  proposals: ProposalRow[];
}) {
  const [editor, setEditor] = useState<EditorState>({ open: false, editing: null });
  const [expanded, setExpanded] = useState<Set<number>>(new Set());
  const [retroactive, setRetroactive] = useState<RetroactiveModalState>(CLOSED_RETROACTIVE_MODAL);
  const [pending, startTransition] = useTransition();

  const categoryName = useMemo(() => {
    const map = new Map(categories.map((c) => [c.slug, c.name]));
    return (slug: string) => map.get(slug) ?? slug;
  }, [categories]);

  function openCreate() {
    setEditor({ open: true, editing: null });
  }
  function openEdit(row: RuleRow) {
    setEditor({ open: true, editing: row });
  }
  function close() {
    setEditor({ open: false, editing: null });
  }
  function toggleExpand(id: number) {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function onToggle(row: RuleRow) {
    startTransition(async () => {
      const result = await toggleRuleActive({ id: row.id, active: !row.active });
      if (result.status === "error") toast.error(result.message);
      else toast.success(row.active ? "Regla desactivada" : "Regla activada");
    });
  }

  function onDelete(row: RuleRow) {
    if (!confirm(`Eliminar regla "${row.pattern}"?`)) return;
    startTransition(async () => {
      const result = await deleteRule({ id: row.id });
      if (result.status === "error") toast.error(result.message);
      else toast.success("Regla eliminada");
    });
  }

  function openRetroactiveIfAny(
    ruleId: number,
    preview: RulePreview,
    targetCategorySlug: string,
    successMsg: string,
  ) {
    toast.success(successMsg);
    if (preview.matchCount > 0) {
      setRetroactive({ open: true, ruleId, preview, targetCategorySlug });
    }
  }

  function onApproveProposal(p: ProposalRow) {
    startTransition(async () => {
      const result = await approveRuleProposal({ id: p.id });
      if (result.status === "error") {
        toast.error(result.message);
        return;
      }
      openRetroactiveIfAny(
        result.ruleId,
        result.preview,
        p.categorySlug,
        `Regla creada: %${p.merchant}% → ${categoryName(p.categorySlug)}`,
      );
    });
  }

  function onRevertRetroactive(row: RuleRow) {
    if (
      !confirm(
        `Revertir ${row.retroactiveMatchCount} ${row.retroactiveMatchCount === 1 ? "transacción" : "transacciones"} aplicada${row.retroactiveMatchCount === 1 ? "" : "s"} por esta regla? Volverán a su categoría previa.`,
      )
    ) {
      return;
    }
    startTransition(async () => {
      const result = await revertRuleRetroactive({ id: row.id });
      if (result.status === "error") {
        toast.error(result.message);
        return;
      }
      toast.success(`Revertidas ${result.updatedCount} transacciones`);
    });
  }

  function onDenyProposal(p: ProposalRow) {
    startTransition(async () => {
      const result = await denyRuleProposal({ id: p.id });
      if (result.status === "error") toast.error(result.message);
      else toast.success("Propuesta descartada — no se volverá a sugerir por 30 días");
    });
  }

  function onDowngrade(row: RuleRow) {
    if (!confirm(`Convertir a regla manual? Perderás el trail de auto-generación.`)) return;
    startTransition(async () => {
      const result = await downgradeAutoGeneratedRule({ id: row.id });
      if (result.status === "error") toast.error(result.message);
      else toast.success("Regla convertida a manual");
    });
  }

  return (
    <div className="flex flex-col gap-4">
      {proposals.length > 0 ? (
        <Card className="border-amber-300 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/30">
          <CardHeader>
            <CardTitle className="text-amber-900 dark:text-amber-200">
              🤖 {proposals.length} sugerencia{proposals.length !== 1 ? "s" : ""} del learning loop
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-2">
            {proposals.map((p) => (
              <div
                key={p.id}
                className="flex flex-wrap items-center gap-2 rounded-md border border-amber-200 bg-white p-2 text-sm dark:border-amber-900 dark:bg-amber-950/40"
                data-testid={`proposal-row-${p.id}`}
              >
                <div className="flex-1">
                  <span className="font-mono">%{p.merchant}%</span>{" "}
                  <span className="text-muted-foreground">→</span>{" "}
                  <span className="font-medium">{categoryName(p.categorySlug)}</span>
                  <span className="text-muted-foreground ml-2 text-xs">
                    ({p.correctionTxnIds.length} correcciones en 30 d)
                  </span>
                </div>
                <Button
                  variant="default"
                  size="sm"
                  onClick={() => onApproveProposal(p)}
                  disabled={pending}
                >
                  Aprobar
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => onDenyProposal(p)}
                  disabled={pending}
                >
                  Descartar
                </Button>
              </div>
            ))}
          </CardContent>
        </Card>
      ) : null}

      <div className="flex justify-end">
        <Button onClick={openCreate}>
          <PlusIcon className="size-4" />
          Nueva regla
        </Button>
      </div>

      {rules.length === 0 ? (
        <Card>
          <CardContent className="text-muted-foreground flex flex-col items-center gap-2 py-12 text-center text-sm">
            <p>No tenés reglas todavía.</p>
            <p>
              Creá una regla manual con un patrón ILIKE (por ejemplo <code>%CARULLA%</code>) y una
              categoría destino.
            </p>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardHeader>
            <CardTitle>
              {rules.length} regla{rules.length !== 1 ? "s" : ""} ·{" "}
              {rules.filter((r) => r.active).length} activas ·{" "}
              {rules.filter((r) => r.autoGenerated).length} auto-generadas
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto rounded-md border">
              <table className="w-full text-sm">
                <thead className="bg-muted/50 text-muted-foreground text-xs uppercase">
                  <tr>
                    <th className="w-8 p-2"></th>
                    <th className="w-12 p-2 text-left">#</th>
                    <th className="p-2 text-left">Patrón</th>
                    <th className="p-2 text-left">Categoría</th>
                    <th className="p-2 text-right">Prioridad</th>
                    <th className="p-2 text-right">Hits</th>
                    <th className="p-2 text-left">Último</th>
                    <th className="p-2 text-left">Origen</th>
                    <th className="p-2 text-left">Estado</th>
                    <th className="p-2"></th>
                  </tr>
                </thead>
                <tbody>
                  {rules.map((r) => {
                    const isExpanded = expanded.has(r.id);
                    const corrections = r.generatedFromCorrections ?? [];
                    const canExpand = r.autoGenerated && corrections.length > 0;
                    return (
                      <Fragment key={r.id}>
                        <tr
                          id={`rule-${r.id}`}
                          className={cn(
                            "scroll-mt-20 border-t transition-colors",
                            // #334: when the URL hash matches this row's id
                            // (e.g. navigating from the "¿Por qué?" modal's
                            // "Ver Regla #N" link), flash a visible highlight
                            // so the user can tell which row is the one they
                            // were sent to. Pure CSS — no JS, no state.
                            "target:bg-amber-100 target:ring-2 target:ring-amber-400 target:ring-inset dark:target:bg-amber-900/40",
                            !r.active && "opacity-50",
                          )}
                          data-testid={`rule-row-${r.id}`}
                        >
                          <td className="p-2 text-center">
                            {canExpand ? (
                              <button
                                type="button"
                                onClick={() => toggleExpand(r.id)}
                                aria-label={isExpanded ? "Collapse" : "Expand"}
                                className="text-muted-foreground hover:text-foreground"
                              >
                                {isExpanded ? (
                                  <ChevronDownIcon className="size-4" />
                                ) : (
                                  <ChevronRightIcon className="size-4" />
                                )}
                              </button>
                            ) : null}
                          </td>
                          <td className="text-muted-foreground p-2 font-mono text-xs tabular-nums">
                            {r.id}
                          </td>
                          <td className="p-2 font-mono text-xs">{r.pattern}</td>
                          <td className="p-2">
                            <div className="font-medium">{categoryName(r.categorySlug)}</div>
                            <div className="text-muted-foreground text-xs">{r.categorySlug}</div>
                          </td>
                          <td className="p-2 text-right tabular-nums">{r.priority}</td>
                          <td className="p-2 text-right tabular-nums">{r.hitCount}</td>
                          <td className="text-muted-foreground p-2 text-xs">
                            {formatRelative(r.lastHitAt)}
                          </td>
                          <td className="p-2 text-xs">
                            {r.autoGenerated ? (
                              <span className="rounded bg-violet-100 px-1.5 py-0.5 text-violet-900 dark:bg-violet-950 dark:text-violet-200">
                                🤖 auto
                                {corrections.length > 0 ? ` · ${corrections.length}` : ""}
                              </span>
                            ) : (
                              <span className="text-muted-foreground">✍ manual</span>
                            )}
                          </td>
                          <td className="p-2 text-xs">
                            <button
                              type="button"
                              onClick={() => onToggle(r)}
                              disabled={pending}
                              className={cn(
                                "rounded px-1.5 py-0.5",
                                r.active
                                  ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200"
                                  : "bg-muted text-muted-foreground",
                              )}
                            >
                              {r.active ? "activa" : "pausada"}
                            </button>
                          </td>
                          <td className="p-2 text-right">
                            <div className="flex justify-end gap-1">
                              {r.retroactiveMatchCount > 0 ? (
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => onRevertRetroactive(r)}
                                  disabled={pending}
                                  aria-label="Revert retroactive matches"
                                  title={`${r.retroactiveMatchCount} retroactivas · revertir`}
                                  className="text-amber-700 dark:text-amber-300"
                                  data-testid={`revert-retroactive-${r.id}`}
                                >
                                  <Undo2Icon className="size-4" />
                                  <span className="ml-1 tabular-nums">
                                    {r.retroactiveMatchCount}
                                  </span>
                                </Button>
                              ) : null}
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => openEdit(r)}
                                disabled={pending}
                                aria-label="Edit"
                              >
                                <PencilIcon className="size-4" />
                              </Button>
                              {r.autoGenerated ? (
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => onDowngrade(r)}
                                  disabled={pending}
                                  aria-label="Downgrade to manual"
                                  title="Convertir a manual"
                                >
                                  ✍
                                </Button>
                              ) : null}
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => onDelete(r)}
                                disabled={pending}
                                aria-label="Delete"
                              >
                                <Trash2Icon className="size-4" />
                              </Button>
                            </div>
                          </td>
                        </tr>
                        {isExpanded && canExpand ? (
                          <tr className="bg-muted/30">
                            <td></td>
                            <td colSpan={9} className="text-muted-foreground p-2 text-xs">
                              <span className="font-medium">Generada por correcciones:</span>{" "}
                              {corrections.map((txId, i) => (
                                <span key={txId}>
                                  <span className="font-mono">#{txId}</span>
                                  {i < corrections.length - 1 ? ", " : ""}
                                </span>
                              ))}
                            </td>
                          </tr>
                        ) : null}
                      </Fragment>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      <RuleEditor
        key={editor.editing?.id ?? (editor.open ? "new" : "closed")}
        open={editor.open}
        editing={editor.editing}
        categories={categories}
        onClose={close}
        onCreated={(ruleId, preview, categorySlug) =>
          openRetroactiveIfAny(ruleId, preview, categorySlug, "Regla creada")
        }
      />

      <ApplyRetroactiveModal
        open={retroactive.open}
        ruleId={retroactive.ruleId}
        preview={retroactive.preview}
        targetCategoryName={
          retroactive.targetCategorySlug ? categoryName(retroactive.targetCategorySlug) : null
        }
        categoryName={categoryName}
        onClose={() => setRetroactive(CLOSED_RETROACTIVE_MODAL)}
      />
    </div>
  );
}

function RuleEditor({
  open,
  editing,
  categories,
  onClose,
  onCreated,
}: {
  open: boolean;
  editing: RuleRow | null;
  categories: CategoryOption[];
  onClose: () => void;
  onCreated: (ruleId: number, preview: RulePreview, categorySlug: string) => void;
}) {
  const [pending, startTransition] = useTransition();
  const [pattern, setPattern] = useState(editing?.pattern ?? "");
  const [categorySlug, setCategorySlug] = useState(
    editing?.categorySlug ?? categories[0]?.slug ?? "",
  );
  const [priority, setPriority] = useState(editing?.priority.toString() ?? "100");

  function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    const trimmed = pattern.trim();
    if (!trimmed) {
      toast.error("El patrón no puede estar vacío.");
      return;
    }
    const pri = Number(priority);
    if (!Number.isInteger(pri) || pri < 1 || pri > 10000) {
      toast.error("La prioridad debe ser un entero entre 1 y 10000.");
      return;
    }
    if (!categorySlug) {
      toast.error("Elegí una categoría.");
      return;
    }
    startTransition(async () => {
      if (editing) {
        const result = await updateRule({
          id: editing.id,
          pattern: trimmed,
          categorySlug,
          priority: pri,
        });
        if (result.status === "error") {
          toast.error(result.message);
          return;
        }
        toast.success("Regla actualizada");
        onClose();
        return;
      }
      const result = await createRule({
        pattern: trimmed,
        categorySlug,
        priority: pri,
      });
      if (result.status === "error") {
        toast.error(result.message);
        return;
      }
      onClose();
      onCreated(result.ruleId, result.preview, categorySlug);
    });
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        if (!next) onClose();
      }}
    >
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>{editing ? "Editar regla" : "Nueva regla"}</DialogTitle>
        </DialogHeader>
        <form onSubmit={onSubmit} className="flex flex-col gap-3">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="rule-pattern">Patrón (ILIKE)</Label>
            <Input
              id="rule-pattern"
              value={pattern}
              onChange={(e) => setPattern(e.target.value)}
              placeholder="%CARULLA%"
              required
              maxLength={200}
              autoFocus={!editing}
              className="font-mono"
            />
            <p className="text-muted-foreground text-xs">
              Matcheo contra descripción limpia o merchant. Usá <code>%</code> como comodín.
            </p>
          </div>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="rule-category">Categoría destino</Label>
            <select
              id="rule-category"
              value={categorySlug}
              onChange={(e) => setCategorySlug(e.target.value)}
              className="bg-background h-9 rounded-md border px-2 text-sm"
              required
            >
              {categories.map((c) => (
                <option key={c.slug} value={c.slug}>
                  {c.parentSlug ? `↳ ${c.name}` : c.name}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="rule-priority">Prioridad</Label>
            <Input
              id="rule-priority"
              type="number"
              min="1"
              max="10000"
              value={priority}
              onChange={(e) => setPriority(e.target.value)}
              required
              className="tabular-nums"
            />
            <p className="text-muted-foreground text-xs">
              Menor número = se evalúa primero. Default: 100.
            </p>
          </div>

          <DialogFooter className="mt-2">
            <Button type="button" variant="outline" onClick={onClose} disabled={pending}>
              Cancelar
            </Button>
            <Button type="submit" disabled={pending}>
              {pending ? "Guardando…" : editing ? "Guardar" : "Crear"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
