import { NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { classificationRules, emailReceipts, transactions } from "@/lib/db/schema";
import { notDeleted } from "@/lib/db/helpers";
import { getSessionUserOrNull } from "@/lib/auth/session";
import { aiReasonText, asReason, receiptIdFromReason } from "@/lib/classification/reason";
import { findMatchingRule } from "@/lib/classification/rules";
import type { ClassificationMethod } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type RuleDetail = {
  id: number;
  pattern: string;
  categorySlug: string;
  autoGenerated: boolean;
  createdAt: string;
  generatedFromCorrections: number[] | null;
};

// #809: classify-sweep's prior-art pass writes `method = 'rule_retroactive'`
// WITHOUT a `retroactive_rule_id` — no `classification_rules` row was ever
// involved, so there is nothing to point that FK at. Detected via the
// `classification_reason` marker instead. Must be checked BEFORE the
// rule-lookup branch below, or a prior-art row falls through to "no rule
// matched" and renders a factually wrong explanation.
type PriorArtDetail = {
  categorySlug: string;
  manualCount: number;
  totalCount: number;
};

export type ReceiptCitationDetail = {
  id: number;
  merchant: string | null;
  gateway: string;
  matchKind: string | null;
};

export type ClassificationReasonResponse =
  | {
      method: "rule" | "rule_retroactive";
      summary: string;
      detail: {
        rule: RuleDetail | null;
        priorArt: PriorArtDetail | null;
        receipt: ReceiptCitationDetail | null;
      };
    }
  | {
      method: "ai";
      summary: string;
      detail: {
        confidence: number | null;
        reason: string | null;
        receipt: ReceiptCitationDetail | null;
      };
    }
  | {
      method: "manual";
      summary: string;
      detail: {
        previousCategorySlug: string | null;
        updatedAt: string;
      };
    }
  | {
      method: "manual_confirmed";
      summary: string;
      detail: {
        originalMethod: ClassificationMethod | null;
        originalConfidence: number | null;
      };
    }
  | {
      method: "unclassified";
      summary: string;
      detail: null;
    };

function parsePriorArtReason(raw: unknown): PriorArtDetail | null {
  const parsed = asReason(raw);
  if (!parsed || parsed.action !== "prior_art" || typeof parsed.categorySlug !== "string") {
    return null;
  }
  return {
    categorySlug: parsed.categorySlug,
    manualCount: typeof parsed.manualCount === "number" ? parsed.manualCount : 0,
    totalCount: typeof parsed.totalCount === "number" ? parsed.totalCount : 0,
  };
}

function parseConfirmedReason(raw: unknown): {
  originalMethod: ClassificationMethod | null;
  originalConfidence: number | null;
} {
  const parsed = asReason(raw);
  if (!parsed) return { originalMethod: null, originalConfidence: null };
  const from = typeof parsed.confirmed_from === "string" ? parsed.confirmed_from : null;
  const conf = typeof parsed.confidence === "number" ? parsed.confidence : null;
  return {
    originalMethod: from as ClassificationMethod | null,
    originalConfidence: conf,
  };
}

async function loadReceiptCitation(
  userId: number,
  raw: unknown,
): Promise<ReceiptCitationDetail | null> {
  const reason = asReason(raw);
  const receiptId = receiptIdFromReason(reason);
  if (receiptId == null) return null;
  const [row] = await db
    .select({
      id: emailReceipts.id,
      merchant: emailReceipts.merchant,
      gateway: emailReceipts.gateway,
    })
    .from(emailReceipts)
    .where(
      and(
        eq(emailReceipts.userId, userId),
        eq(emailReceipts.id, receiptId),
        notDeleted(emailReceipts.deletedAt),
      ),
    )
    .limit(1);
  if (!row) return null;
  return {
    id: row.id,
    merchant: row.merchant,
    gateway: row.gateway,
    matchKind: typeof reason?.matchKind === "string" ? reason.matchKind : null,
  };
}

export async function GET(
  _req: Request,
  context: { params: Promise<{ id: string }> },
): Promise<NextResponse<ClassificationReasonResponse | { error: string }>> {
  const session = await getSessionUserOrNull();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id: idParam } = await context.params;
  const id = Number.parseInt(idParam, 10);
  if (!Number.isFinite(id) || id <= 0) {
    return NextResponse.json({ error: "Invalid id" }, { status: 400 });
  }

  const [txn] = await db
    .select({
      id: transactions.id,
      descriptionRaw: transactions.descriptionRaw,
      descriptionClean: transactions.descriptionClean,
      merchant: transactions.merchant,
      categorySlug: transactions.categorySlug,
      classificationMethod: transactions.classificationMethod,
      classificationConfidence: transactions.classificationConfidence,
      classificationReason: transactions.classificationReason,
      previousCategorySlug: transactions.previousCategorySlug,
      retroactiveRuleId: transactions.retroactiveRuleId,
      updatedAt: transactions.updatedAt,
    })
    .from(transactions)
    .where(
      and(
        eq(transactions.userId, session.id),
        eq(transactions.id, id),
        notDeleted(transactions.deletedAt),
      ),
    )
    .limit(1);

  if (!txn) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  switch (txn.classificationMethod) {
    case "rule":
    case "rule_retroactive": {
      const receipt = await loadReceiptCitation(session.id, txn.classificationReason);
      const priorArt = parsePriorArtReason(txn.classificationReason);
      if (priorArt) {
        const summary =
          priorArt.manualCount >= 1
            ? `Basado en una decisión manual tuya para este mismo comercio → ${priorArt.categorySlug}`
            : `Basado en ${priorArt.totalCount} transacciones previas de este comercio clasificadas como ${priorArt.categorySlug}`;
        return NextResponse.json({
          method: txn.classificationMethod,
          summary,
          detail: { rule: null, priorArt, receipt },
        });
      }

      const ruleId = txn.retroactiveRuleId;
      let rule: RuleDetail | null = null;
      if (ruleId) {
        // Retroactive: rule is known by FK, prefer it over pattern re-match.
        const [row] = await db
          .select({
            id: classificationRules.id,
            pattern: classificationRules.pattern,
            categorySlug: classificationRules.categorySlug,
            autoGenerated: classificationRules.autoGenerated,
            createdAt: classificationRules.createdAt,
            generatedFromCorrections: classificationRules.generatedFromCorrections,
          })
          .from(classificationRules)
          .where(
            and(eq(classificationRules.userId, session.id), eq(classificationRules.id, ruleId)),
          )
          .limit(1);
        if (row) {
          rule = {
            id: row.id,
            pattern: row.pattern,
            categorySlug: row.categorySlug,
            autoGenerated: row.autoGenerated,
            createdAt: row.createdAt.toISOString(),
            generatedFromCorrections: row.generatedFromCorrections,
          };
        }
      } else {
        const matched = await findMatchingRule(session.id, {
          descriptionRaw: txn.descriptionRaw,
          descriptionClean: txn.descriptionClean,
          merchant: txn.merchant,
        });
        if (matched) {
          const [row] = await db
            .select({
              id: classificationRules.id,
              pattern: classificationRules.pattern,
              categorySlug: classificationRules.categorySlug,
              autoGenerated: classificationRules.autoGenerated,
              createdAt: classificationRules.createdAt,
              generatedFromCorrections: classificationRules.generatedFromCorrections,
            })
            .from(classificationRules)
            .where(eq(classificationRules.id, matched.id))
            .limit(1);
          if (row) {
            rule = {
              id: row.id,
              pattern: row.pattern,
              categorySlug: row.categorySlug,
              autoGenerated: row.autoGenerated,
              createdAt: row.createdAt.toISOString(),
              generatedFromCorrections: row.generatedFromCorrections,
            };
          }
        }
      }

      const summary = rule
        ? `Regla #${rule.id}: \`${rule.pattern}\` → ${rule.categorySlug}`
        : `Clasificado por una regla que ya no coincide con esta transacción`;

      return NextResponse.json({
        method: txn.classificationMethod,
        summary,
        detail: { rule, priorArt: null, receipt },
      });
    }

    case "ai": {
      const conf = txn.classificationConfidence;
      const parsed = asReason(txn.classificationReason);
      const reason =
        aiReasonText(parsed) ??
        (typeof txn.classificationReason === "string" ? txn.classificationReason : null);
      const receipt = await loadReceiptCitation(session.id, txn.classificationReason);
      const summary = `Claude clasificó como ${txn.categorySlug ?? "—"}${
        conf !== null ? ` (confianza ${conf}%)` : ""
      }`;
      return NextResponse.json({
        method: "ai",
        summary,
        detail: { confidence: conf, reason, receipt },
      });
    }

    case "manual": {
      const prior = txn.previousCategorySlug;
      const summary = prior
        ? `Clasificado manualmente (antes era ${prior})`
        : `Clasificado manualmente`;
      return NextResponse.json({
        method: "manual",
        summary,
        detail: {
          previousCategorySlug: prior,
          updatedAt: txn.updatedAt.toISOString(),
        },
      });
    }

    case "manual_confirmed": {
      const { originalMethod, originalConfidence } = parseConfirmedReason(txn.classificationReason);
      const suffix =
        originalMethod && originalConfidence !== null
          ? ` (original: ${originalMethod} ${originalConfidence}%)`
          : "";
      return NextResponse.json({
        method: "manual_confirmed",
        summary: `Confirmado desde el inbox de revisión${suffix}`,
        detail: { originalMethod, originalConfidence },
      });
    }

    case "unclassified":
    default:
      return NextResponse.json({
        method: "unclassified",
        summary: "Sin clasificar todavía",
        detail: null,
      });
  }
}
