import { NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { classificationRules, transactions } from "@/lib/db/schema";
import { getSessionUserOrNull } from "@/lib/auth/session";
import { findMatchingRule } from "@/lib/classification/rules";
import type { ClassificationMethod } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type RuleDetail = {
  id: number;
  pattern: string;
  categorySlug: string;
  autoGenerated: boolean;
  createdAt: string;
  generatedFromCorrections: number[] | null;
};

export type ClassificationReasonResponse =
  | {
      method: "rule" | "rule_retroactive";
      summary: string;
      detail: { rule: RuleDetail | null };
    }
  | {
      method: "ai";
      summary: string;
      detail: { confidence: number | null; reason: string | null };
    }
  | {
      method: "manual";
      summary: string;
      detail: {
        previousCategorySlug: string | null;
        updatedAt: string;
      };
    }
  | {
      method: "manual_confirmed";
      summary: string;
      detail: {
        originalMethod: ClassificationMethod | null;
        originalConfidence: number | null;
      };
    }
  | {
      method: "unclassified";
      summary: string;
      detail: null;
    };

function parseConfirmedReason(raw: string | null): {
  originalMethod: ClassificationMethod | null;
  originalConfidence: number | null;
} {
  if (!raw) return { originalMethod: null, originalConfidence: null };
  try {
    const parsed = JSON.parse(raw) as { confirmed_from?: unknown; confidence?: unknown };
    const from = typeof parsed.confirmed_from === "string" ? parsed.confirmed_from : null;
    const conf = typeof parsed.confidence === "number" ? parsed.confidence : null;
    return {
      originalMethod: from as ClassificationMethod | null,
      originalConfidence: conf,
    };
  } catch {
    return { originalMethod: null, originalConfidence: null };
  }
}

export async function GET(
  _req: Request,
  context: { params: Promise<{ id: string }> },
): Promise<NextResponse<ClassificationReasonResponse | { error: string }>> {
  const session = await getSessionUserOrNull();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id: idParam } = await context.params;
  const id = Number.parseInt(idParam, 10);
  if (!Number.isFinite(id) || id <= 0) {
    return NextResponse.json({ error: "Invalid id" }, { status: 400 });
  }

  const [txn] = await db
    .select({
      id: transactions.id,
      descriptionRaw: transactions.descriptionRaw,
      descriptionClean: transactions.descriptionClean,
      merchant: transactions.merchant,
      categorySlug: transactions.categorySlug,
      classificationMethod: transactions.classificationMethod,
      classificationConfidence: transactions.classificationConfidence,
      classificationReason: transactions.classificationReason,
      previousCategorySlug: transactions.previousCategorySlug,
      retroactiveRuleId: transactions.retroactiveRuleId,
      updatedAt: transactions.updatedAt,
    })
    .from(transactions)
    .where(and(eq(transactions.userId, session.id), eq(transactions.id, id)))
    .limit(1);

  if (!txn) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  switch (txn.classificationMethod) {
    case "rule":
    case "rule_retroactive": {
      const ruleId = txn.retroactiveRuleId;
      let rule: RuleDetail | null = null;
      if (ruleId) {
        // Retroactive: rule is known by FK, prefer it over pattern re-match.
        const [row] = await db
          .select({
            id: classificationRules.id,
            pattern: classificationRules.pattern,
            categorySlug: classificationRules.categorySlug,
            autoGenerated: classificationRules.autoGenerated,
            createdAt: classificationRules.createdAt,
            generatedFromCorrections: classificationRules.generatedFromCorrections,
          })
          .from(classificationRules)
          .where(
            and(eq(classificationRules.userId, session.id), eq(classificationRules.id, ruleId)),
          )
          .limit(1);
        if (row) {
          rule = {
            id: row.id,
            pattern: row.pattern,
            categorySlug: row.categorySlug,
            autoGenerated: row.autoGenerated,
            createdAt: row.createdAt.toISOString(),
            generatedFromCorrections: row.generatedFromCorrections,
          };
        }
      } else {
        const matched = await findMatchingRule(session.id, {
          descriptionRaw: txn.descriptionRaw,
          descriptionClean: txn.descriptionClean,
          merchant: txn.merchant,
        });
        if (matched) {
          const [row] = await db
            .select({
              id: classificationRules.id,
              pattern: classificationRules.pattern,
              categorySlug: classificationRules.categorySlug,
              autoGenerated: classificationRules.autoGenerated,
              createdAt: classificationRules.createdAt,
              generatedFromCorrections: classificationRules.generatedFromCorrections,
            })
            .from(classificationRules)
            .where(eq(classificationRules.id, matched.id))
            .limit(1);
          if (row) {
            rule = {
              id: row.id,
              pattern: row.pattern,
              categorySlug: row.categorySlug,
              autoGenerated: row.autoGenerated,
              createdAt: row.createdAt.toISOString(),
              generatedFromCorrections: row.generatedFromCorrections,
            };
          }
        }
      }

      const summary = rule
        ? `Regla #${rule.id}: \`${rule.pattern}\` → ${rule.categorySlug}`
        : `Clasificado por una regla que ya no coincide con esta transacción`;

      return NextResponse.json({
        method: txn.classificationMethod,
        summary,
        detail: { rule },
      });
    }

    case "ai": {
      const conf = txn.classificationConfidence;
      const reason = txn.classificationReason;
      const summary = `Claude clasificó como ${txn.categorySlug ?? "—"}${
        conf !== null ? ` (confianza ${conf}%)` : ""
      }`;
      return NextResponse.json({
        method: "ai",
        summary,
        detail: { confidence: conf, reason },
      });
    }

    case "manual": {
      const prior = txn.previousCategorySlug;
      const summary = prior
        ? `Clasificado manualmente (antes era ${prior})`
        : `Clasificado manualmente`;
      return NextResponse.json({
        method: "manual",
        summary,
        detail: {
          previousCategorySlug: prior,
          updatedAt: txn.updatedAt.toISOString(),
        },
      });
    }

    case "manual_confirmed": {
      const { originalMethod, originalConfidence } = parseConfirmedReason(txn.classificationReason);
      const suffix =
        originalMethod && originalConfidence !== null
          ? ` (original: ${originalMethod} ${originalConfidence}%)`
          : "";
      return NextResponse.json({
        method: "manual_confirmed",
        summary: `Confirmado desde el inbox de revisión${suffix}`,
        detail: { originalMethod, originalConfidence },
      });
    }

    case "unclassified":
    default:
      return NextResponse.json({
        method: "unclassified",
        summary: "Sin clasificar todavía",
        detail: null,
      });
  }
}
