"use client";

import { useState } from "react";
import Link from "next/link";
import { HelpCircleIcon, SparklesIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import type { ClassificationMethod } from "@/lib/types";
import type { ClassificationReasonResponse } from "@/app/api/transactions/[id]/classification-reason/route";

type Props = {
  txId: number;
  method: ClassificationMethod;
};

function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("es-CO", { day: "2-digit", month: "short", year: "numeric" });
}

export function ClassificationReasonDialog({ txId, method }: Props) {
  const [open, setOpen] = useState(false);
  const [data, setData] = useState<ClassificationReasonResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Event-driven fetch on open (not useEffect) — avoids react-hooks/set-state-in-effect
  // cascade warnings and keeps the first paint cheap when the modal is closed.
  async function handleOpenChange(next: boolean) {
    setOpen(next);
    if (!next || data) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/transactions/${txId}/classification-reason`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setData((await res.json()) as ClassificationReasonResponse);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Error");
    } finally {
      setLoading(false);
    }
  }

  if (method === "unclassified") {
    // Nothing useful to explain for unclassified rows — the inbox handles those.
    return null;
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <button
          type="button"
          className="text-muted-foreground hover:text-foreground inline-flex items-center gap-1 rounded-md border border-dashed px-1.5 py-0.5 text-[11px] font-normal"
          aria-label="¿Por qué esta categoría?"
          title="¿Por qué esta categoría?"
          data-testid={`classification-reason-${txId}`}
        >
          <HelpCircleIcon className="size-3" />
          ¿Por qué?
        </button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <SparklesIcon className="size-4" />
            ¿Por qué esta categoría?
          </DialogTitle>
          <DialogDescription>{loading ? "Cargando…" : (data?.summary ?? "")}</DialogDescription>
        </DialogHeader>

        {error ? <p className="text-destructive text-sm">Error: {error}</p> : null}

        {!loading && data ? <DetailPanel data={data} /> : null}

        <DialogFooter>
          <Button type="button" variant="outline" onClick={() => setOpen(false)}>
            Cerrar
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function DetailPanel({ data }: { data: ClassificationReasonResponse }) {
  if (data.method === "rule" || data.method === "rule_retroactive") {
    const rule = data.detail.rule;
    if (!rule) {
      return (
        <p className="text-muted-foreground text-sm">
          La regla que aplicó ya no existe o fue modificada. La categoría sigue siendo la asignada.
        </p>
      );
    }
    return (
      <dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1.5 text-sm">
        <dt className="text-muted-foreground">Patrón</dt>
        <dd className="font-mono text-xs">{rule.pattern}</dd>
        <dt className="text-muted-foreground">Destino</dt>
        <dd>{rule.categorySlug}</dd>
        <dt className="text-muted-foreground">Origen</dt>
        <dd>
          {rule.autoGenerated
            ? `🤖 auto-generada${
                rule.generatedFromCorrections && rule.generatedFromCorrections.length > 0
                  ? ` (${rule.generatedFromCorrections.length} correcciones)`
                  : ""
              }`
            : "✍ manual"}
        </dd>
        <dt className="text-muted-foreground">Creada</dt>
        <dd>{formatDate(rule.createdAt)}</dd>
        <dt className="text-muted-foreground">Ver</dt>
        <dd>
          <Link
            href={`/settings/rules#rule-${rule.id}`}
            className="text-primary underline-offset-4 hover:underline"
          >
            Regla #{rule.id}
          </Link>
        </dd>
      </dl>
    );
  }

  if (data.method === "ai") {
    return (
      <dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1.5 text-sm">
        <dt className="text-muted-foreground">Confianza</dt>
        <dd>{data.detail.confidence !== null ? `${data.detail.confidence}%` : "—"}</dd>
        <dt className="text-muted-foreground">Razón</dt>
        <dd>{data.detail.reason ?? <span className="text-muted-foreground">(sin razón)</span>}</dd>
      </dl>
    );
  }

  if (data.method === "manual") {
    return (
      <dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1.5 text-sm">
        <dt className="text-muted-foreground">Categoría previa</dt>
        <dd>
          {data.detail.previousCategorySlug ?? (
            <span className="text-muted-foreground">(primera asignación)</span>
          )}
        </dd>
        <dt className="text-muted-foreground">Actualizada</dt>
        <dd>{formatDate(data.detail.updatedAt)}</dd>
      </dl>
    );
  }

  if (data.method === "manual_confirmed") {
    return (
      <dl className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-1.5 text-sm">
        <dt className="text-muted-foreground">Método original</dt>
        <dd>{data.detail.originalMethod ?? "—"}</dd>
        <dt className="text-muted-foreground">Confianza original</dt>
        <dd>
          {data.detail.originalConfidence !== null ? `${data.detail.originalConfidence}%` : "—"}
        </dd>
      </dl>
    );
  }

  return null;
}
